### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by yokrysty** [CYCOABHI/LoL-Account-Checker-PuppyLover101#3]
KID STOP EDITING MY MESSAGES AND STOP STEALING MY CODE!

**Comment by Sorgie19** [comment]
It means that the person hasnt played in a LONG time and so they NEED to change pw.

**Comment by yokrysty** [comment]
And where is your update? To update doesn't mean to change some values in settings.json
Mine is updated to 6.10, the compiled version (downloadable zip file).
The code isn't updated since 6.6 because a lot of people steals the code and sell it (not your case).

**Comment by Sorgie19** [comment]
I'm new to github, and sorry if I came off as rude.
I thought that this was forked and not just a total rip off of your program.

The only reason I thought yours wasn't updated was because the files say 6.6
Once again I'm sorry

**Comment by CYCOABHI** [comment]
Yep that is correct, Some very old accounts (under 2011 I believe) have it.
